### ISSUE TITLE
As a developer I would like to deploy Greens as a docker container

### ISSUE THREAD

**Issue by seanlw** [uhlibraries-digital/greens#10]
Review and incorporate docker scripts provided by @medined.

https://github.com/medined/docker-greens

Conversation can also be found in https://github.com/uhlibraries-digital/greens/issues/8

**Comment by medined** [comment]
I release my code and comments to the public domain. Unless asked, I don't intend to evolve the code past its current form. Once the code is in a uhlibraries-digital project, I will add a pointer to that project from mine. I will mention that forked projects are not findable or searching in github (something that I recently found out). Therefore, I recommend creating a new uhlibraries-digital/docker-greens project. But I won't be insulted if you follow another path. ::))

**Comment by seanlw** [comment]
@medined I don't intend to just fork the project, like you said github search doesn't work for forked projects :(. I'll be reviewing your project and determine the best option moving forward. This isn't a high priority ATM so it might be awhile before I can get to it. Thank you for your contribution, it's greatly appreciated.

**Comment by metaweidner** [comment]
@seanlw Is this still needed? If yes, I'll create a new story. If not, please close.

**Comment by seanlw** [comment]
@metaweidner yes, but low priority 'nice-to-have'

**Comment by metaweidner** [comment]
Transferred to Trello.
