### ISSUE TITLE
As a develop if the noid template changes, the noid state should be refreshed.

### ISSUE THREAD

**Issue by seanlw** [uhlibraries-digital/greens#3]
In the event that the noid template changes, the noid states should be refreshed.

Need to see what all that would effect since there could be a identifier collision depending on what the new template is.

**Comment by metaweidner** [comment]
@seanlw Is this still needed? If yes, I'll create a new story. If not, please close.

**Comment by seanlw** [comment]
@metaweidner yes, 'nice-to-have'. low priority.

**Comment by metaweidner** [comment]
Transferred to Trello.
