### ISSUE TITLE
Does Greens check for duplicate ERC What labels?

### ISSUE THREAD

**Issue by metaweidner** [uhlibraries-digital/greens#6]
Desired behavior is No. Some digital objects may have the same title, and duplicate What labels may pop up on iddev during testing.

**Comment by seanlw** [comment]
No, it does not validate that a ERC What is unique.

**Comment by metaweidner** [comment]
TY

**Comment by seanlw** [comment]
Could the ERC What be the same across different prefixes?

**Comment by metaweidner** [comment]
It's a possibility. For example, a photograph of a person (`do` prefix) could have the same Title as that person's prefLabel in Cedar (`au` prefix).

**Comment by seanlw** [comment]
Thanks for clarifying
