### ISSUE TITLE
When 'naan' is empty string, an ark can not be deleted.

### ISSUE THREAD

**Issue by medined** [uhlibraries-digital/greens#8]
When 'naan' is empty in the app.yaml, an ark like 'ark://57x43' is minted. However, when trying to delete that ark using curl, the two slashes are combined somewhere in the process. Therefore, the 'id' that is sought is 'ark:/57x43'. I see two possible resolutions, throw an exception when minted if the 'naan' is empty. Or mint the ark with only one slash in the special case when 'naan' is empty.

**Comment by seanlw** [comment]
The NAAN is a mandatory organization identifier. The ARK shouldn't have been minted in the first place if NAAN is empty.

Thanks for catching this!

**Comment by medined** [comment]
Would a Dockerfile be welcome? And a few bash functions to show how it works?

**Comment by seanlw** [comment]
Yes, they would be welcomed

**Comment by medined** [comment]
https://github.com/medined/docker-greens - I have a bash script that builds and starts an application stack. Please review it. Let me know if anything is unclear.
